### ISSUE TITLE
Implement IDisposable in WatsonCluster classes and call Dispose for WatsonTcp resources

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonCluster#3]
Please implement IDisposable in WatsonCluster classes according to the standard pattern, such that WatsonTcp resources are disposed of when Dispose is called on the ClusterNode / ClusterClient / ClusterServer. Resources may leak otherwise, in theory at least.

Ideally, I would like to call Dispose on the ClusterNode from my own IDisposable, or instantiate my ClusterNode in a using block, and have it release all associated resources when the application is refreshing, rather than rely on the garbage collector and/or process shut down before the connections are guaranteed to be closed / IsHealthy() no longer true on the peer instance.

Willing to help review and test if you do implement this. Thanks!

**Comment by jchristn** [comment]
Hi @brudo !  Just committed and pushed a fix, please let me know your thoughts.  Thanks for making the library better.  https://github.com/jchristn/WatsonCluster/commit/c476403414c2b21aa11131908b9deae31b2a1dd8

**Comment by brudo** [comment]
I tested; it does not cause a regression and now does support the disposable resource pattern. Thanks to you!
