### ISSUE TITLE
messages may get fragmented and/or truncated

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonCluster#4]
With moderate message volume, communicating between two machines on the same subnet, I found a significant incidence of truncated or fragmented messages such that the received bytes could not be parsed. This would not have been expected with TCP, although with UDP it might be normal. My calling code is multithreaded, but I ensured that only one send was executing at a time, and I notice there is a Flush in your Send implementation. I did not determine whether the issue was in WatsonCluster or WatsonTcp but I suspect it may have something to do with the framing of the messages. The message length may sometimes exceed the MTU.

**Comment by jchristn** [comment]
Hi @brudo thanks again for filing this.  I suspect what's happening is multiple threads attempting to write to the stream concurrently, thus commingling messages.  I should be able to solve this by adding a send lock of sorts to Watson TCP - followed by a NuGet update, then a NuGet update to Watson Cluster.  That way, there can only be one writer to the stream at a time.  I'll give it a go this weekend and keep you posted.  Thanks!

**Comment by brudo** [comment]
I would not have thought so since I was calling Send from inside a synchronized block, but there might not have been any delay between calls. Looking forward to your results; thanks!

**Comment by jchristn** [comment]
Hi @brudo I updated, committed/pushed, and published a new NuGet package v1.0.6.  I added IDisposable (you wanted that on WatsonCluster) as well.  I added a send lock on the client and added two new test projects: TestMultiThread and TestParallel.  In TestMultiThread, multiple threads consume a single WatsonTcpClient instead.  In TestParallel, multiple threads each with their own WatsonTcpClient are sending messages.  In both cases, I have the server check the MD5 of the incoming message and I haven't been able to reproduce a scenario where a message is fragmented/truncated.  I tried with 2, 4, 8, and 16 threads, and 4KB, 8KB, 16KB, 32KB, 64KB, and 256KB message sizes.  Would you mind seeing if you run into the same issue with this update?  Also if you have any feedback on additional test projects I could/should create I'd love to hear from you on it.  BTW - WatsonCluster has not yet been updated, just a heads-up on that.  Cheers!

**Comment by brudo** [comment]
Thanks a lot @jchristn. It sounds like it is probably solved now. It may be a few days before I can test.

**Comment by jchristn** [comment]
My pleasure sir!  I'll close this out for now, feel free to re-open if this doesn't solve it.

**Comment by brudo** [comment]
Following up to confirm, I no longer see messages getting corrupted after this change. Thanks again!

**Comment by jchristn** [comment]
Awesome :)  Thanks @brudo !!
