### ISSUE TITLE
Watson cluster integreity can be disrupted when unexpected clients connect

### ISSUE THREAD

**Issue by brudo** [jchristn/WatsonCluster#6]
I noticed Watson cluster accepts connections not coming from the configured peer instance, and can be confused by these additional connections, causing the cluster to lose coherency. I prevented this in my own code, but the way I did it may not be suited to sharing. I will try to generalize it so that I can offer a pull request. Otherwise, we would have to rely on firewall rules to ensure only the expected peer can connect.

**Comment by jchristn** [comment]
Hi @brudo , would an appropriate solution in your opinion be to allow the caller to specify a source IP to permit connections from, and reject others?  I should be able to make this change fairly quickly

**Comment by brudo** [comment]
Hi@jchristn yes I think so. In fact, see my branch restrict-nonpeer-connections for work in progress. I did not yet implement a way to revert to old behavior, where any IP can connect and participate as peer. Default behavior, if no alternate peer IPs are specified, is that connections from the IP address given in PeerIp are accepted as peers, while all others are non-peers. Also, at this point there is no direct communication to or from any connected clients other than the last valid peer, but the connection is left open. Note, I will be at a conference this week so I may not get to finish it right away but feedback is welcome!

**Comment by jchristn** [comment]
Hi @brudo I added a new constructor to WatsonTcpServer which includes a List<string> for permitted IPs.  The AcceptConnections() loop will check the list (if it's not null/empty) against the source IP of the incoming connection, and close the connection if there is no match.  I committed/pushed and updated NuGet.  One optimization I just realized I could make is to move the comparison outside of the task that is started.  Please let me know what you think!

**Comment by jchristn** [comment]
(and then I can expose it upward to WatsonCluster)

**Comment by brudo** [comment]
OK, that's a good way. I didn't want to touch WatsonTcp for this but am glad to take advantage if you do. Please disregard the branch I created for now and I'll integrate your changes and build on that instead.

Feedback: please have the constructor accept an IEnumerable of strings instead of a List for more flexibility. Just my opinion. But construct a collection from it (e.g. List / Set / etc.) so that you only enumerate it once.

**Comment by jchristn** [comment]
Awesome suggestion, I'll update this right now and then integrate into WatsonCluster.  Will let you know as soon as it's done.

**Comment by jchristn** [comment]
Hi @brudo this is integrated into WatsonCluster.  It automatically populates the permitted IP list with the IP of the peer and passes it directly to WatsonTcpServer, so there are no changes to the APIs in WatsonCluster.  I gave it a test and it worked well.  I've updated Github for both and added new NuGet packages (1.0.10 for WatsonTcp, and 1.0.7 for WatsonCluster).  Thanks again for the help sir, and re-open if you encounter any issues!

**Comment by brudo** [comment]
Actually come to think of it, in my case I did want non-peers to be able to connect and "listen in". But I'll add that back later in a more controlled way once your update is complete.

**Comment by brudo** [comment]
I see the final update... Great!

**Comment by jchristn** [comment]
If you like I can add another constructor that allows the list of permitted IPs to be overridden, will only take me a few minutes - cool?

**Comment by jchristn** [comment]
Just committed this and updated NuGet, please let me know if this helps!

**Comment by brudo** [comment]
Cool! I'll see what I can do with it next week. Now in my worst case I will be able just bypass the filtering at WatsonTcp level, although most likely I will be able to take advantage.

**Comment by brudo** [comment]
Just a follow up, our in-house modified version of WatsonCluster is now updated with a server allow list based on these changes in WatsonTcp. Thanks again!

**Comment by jchristn** [comment]
Glad to hear @brudo !  Thanks for the feedback and help!
